name: Publish NuGet Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0"

      - name: Build Project
        run: dotnet build src/FoodService.Data.Nugget.Pkg/FoodService.Data.Nugget.Pkg.csproj

      - name: Pack NuGet Package
        run: dotnet pack src/FoodService.Data.Nugget.Pkg/FoodService.Data.Nugget.Pkg.csproj -o $(Build.ArtifactStagingDirectory)

      - name: Publish NuGet Package
        run: dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --api-key ${{ secrets.PACKAGES_TOKEN }} --source https://nuget.pkg.github.com/Org-FoodService/index.json
